AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway CLSI

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs20.x
    MemorySize: 128

Resources:

  CLSIApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: UE2APIDESACLSIV1
      StageName: Desa
      EndpointConfiguration: REGIONAL

functions: ./config/function.cloud.yml)}

Outputs:

  ApiUrl:
    Description: "URL del endpoint /hola"
    Value: !Sub "https://${CLSIApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Desa/hola"
